### ISSUE TITLE
в версии 0.0.7 ошибка при вызове Sbp.getAndroidInstalledByPackageNameBanks(...)

### ISSUE THREAD

**Issue by mikhey777** [smenateam/sbp#6]
Привет! в версии 0.0.7 ошибка при вызове Sbp.getAndroidInstalledByPackageNameBanks(...) 
`type '_Map<Object?, Object?>' is not a subtype of type 'String' in type cast`
 
у меня взлетел вот этот вариант (правда возвращает  `List<ApplicationInfoModel>` а не` List<String>` мне так удобней):
```
static Future<List<ApplicationInfoModel>> getAndroidInstalledByPackageNameBanks(List<String> packageNames) async {
    final List<String> packageNameApplications = packageNames;

    final installedBanks = (await _channel
            .invokeMethod('getInstalledBanks', {'application_package_names': packageNameApplications}) as List)
        .map(
          (installedBank) => ApplicationInfoModel.fromJson(installedBank as Map<dynamic, dynamic>),
        )
        .toList();
    return installedBanks;
  }
```

**Comment by Pelmeshka102** [comment]
Можно подробнее о телефоне, на котором произошла ошибка? Также было бы неплохо посмотреть сам код. Вы используете внутренние assetsLinks или файл лежит на отдельном сервере?

Сейчас все переделываю под C2membersModel так как там используются и schema и package_names. Вы используете эту функцию для того, чтобы тянуть иконки из натива? До конца этой неделе постараюсь все поправить и выложить на pub.dev
