### ISSUE TITLE
Краш приложения на IOS 17

### ISSUE THREAD

**Issue by AlexeyVolkhin** [smenateam/sbp#7]
<img width="781" alt="Снимок экрана 2023-11-08 в 16 43 28" src="https://github.com/smenateam/sbp/assets/121279152/ca0c94f8-bcf0-4d20-a873-4fee09d9c11d">
Крашится приложение при попытке получить список банков

Вопрос, будет ли библиотека поддерживаться разработчиками, последнее обновление 3 месяца назад?

**Comment by kherel** [comment]
Есть какое-то решение?

**Comment by Pelmeshka102** [comment]
Возьму в работу на этой неделе

**Comment by Diyor331** [comment]
Если нужно срочно чтобы заработал пакет, вот решение: 

Замените старый код на этот: 

```
public func getInstalledBanks(_ schemaApplications: [String], result: @escaping FlutterResult) {
    var schemas: [String] = []
    for schemaApplication in schemaApplications {
        if let schema = URL(string: "\(schemaApplication)://") {
            if UIApplication.shared.canOpenURL(schema) {
                schemas.append(schemaApplication)
            }
        }
    }
    result(schemas)
}
```

**Comment by AlexeyVolkhin** [comment]
Спасибо за ответ!
Пока реализовал в приложении для 17 ios оплату через web view, жду фикса)

**Comment by Pelmeshka102** [comment]
@Diyor331 спасибо за проделанную работу, новая версия уже доступна в pub.dev
